export const products = [
  {
    id: 1,
    title: "Fone de Ouvido Bluetooth",
    price: 199.9,
    rating: 4,
    tag: "Novo",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 2,
    title: "Smartwatch Resistente à Água",
    price: 349.9,
    rating: 5,
    tag: "Promo",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 3,
    title: "Notebook Gamer 15,6”",
    price: 4999.9,
    rating: 4,
    tag: "Novo",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 4,
    title: "Câmera DSLR Profissional",
    price: 2999.9,
    rating: 5,
    tag: "Promo",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 5,
    title: "Console de Videogame",
    price: 2999.9,
    rating: 4,
    tag: "Novo",
    image: "https://via.placeholder.com/300",
  },
  {
    id: 6,
    title: "Teclado Mecânico RGB",
    price: 499.9,
    rating: 5,
    tag: "Promo",
    image: "https://via.placeholder.com/300",
  },
];
